### ISSUE TITLE
Getting list of open PRs no longer works

### ISSUE THREAD

**Issue by zetok** [softprops/hubcaps#62]
Code worked just fine for almost a month; it even worked yesterday just fine, but today it no longer works.

Line where it fails: https://github.com/zetok/gopull/blob/843d012152f751c38ab39c8cacc937af564944f1/src/gh_interaction.rs#L43

fails with:

```
thread 'main' panicked at 'Failed to get list of PRs: Codec(Syntax(InvalidType(Unit), 1, 46248))', ../src/libcore/result.rs:788
stack backtrace:
   1:     0x559f609dcddf - std::sys::backtrace::tracing::imp::write::h46e546df6e4e4fe6
   2:     0x559f609dfc7b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h077deeda8b799591
   3:     0x559f609df8ff - std::panicking::default_hook::heb8b6fd640571a4f
   4:     0x559f609d408e - std::panicking::rust_panic_with_hook::hd7b83626099d3416
   5:     0x559f609dfec1 - std::panicking::begin_panic::h941ea76fc945d925
   6:     0x559f609d4a1a - std::panicking::begin_panic_fmt::h30280d4dd3f149f5
   7:     0x559f609dfe5e - rust_begin_unwind
   8:     0x559f60a1571f - core::panicking::panic_fmt::h2d3cc8234dde51b4
   9:     0x559f6080c340 - core::result::unwrap_failed::h1e1e300e203e4634
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/macros.rs:29
  10:     0x559f6080c0e5 - _<core..result..Result<T, E>>::expect::h57d9c62efb974bc6
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcore/result.rs:750
  11:     0x559f60800ca2 - gopull::gh_interaction::list_open_pulls::h0872ed321f596244
                        at /home/zetok/git_zetok/rust/gopull/src/gh_interaction.rs:43
  12:     0x559f607ffb22 - gopull::main::h81ddba921818c910
                        at /home/zetok/git_zetok/rust/gopull/src/main.rs:50
  13:     0x559f609df538 - std::panicking::try::call::hca715a47aa047c49
  14:     0x559f609e74db - __rust_try
  15:     0x559f609e747e - __rust_maybe_catch_panic
  16:     0x559f609defde - std::rt::lang_start::h162055cb2e4b9fe7
  17:     0x559f608018e9 - main
  18:     0x7f4fe86ac83b - __libc_start_main
  19:     0x559f607ff7b8 - _start
  20:                0x0 - <unknown>
```

**Comment by zetok** [comment]
Weird, today it started working again(?!), so I'm closing the issue. If it'll stop working I'll reopen.

**Comment by softprops** [comment]
Another helpful tool may be to export the env var RUST_LOG=debug. This project uses the env logger crate.
